# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# Rx
def rx_pods
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'RxSwiftExt', '~> 5'
  pod 'RxGesture', '~> 3'
end

# Network
def network_pods
  pod 'Moya'
  pod 'ReachabilitySwift'
end

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'Cinema' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cinema
  rx_pods
  network_pods

  target 'CinemaTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'CinemaUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      if config.name == 'Local'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end
